### ISSUE TITLE
Integration tests require manually enabling Email/Password authentication on Firebase Console

### ISSUE THREAD

**Issue by MathBunny** [firebase/firebase-admin-dotnet#183]
## Observation

After following the [contributing guide](https://github.com/firebase/firebase-admin-dotnet/blob/master/CONTRIBUTING.md), I was running into some issues running the integration tests. More specifically:

```
Horatius-MacBook-Pro:FirebaseAdmin.IntegrationTests horatiulazu$ dotnet test
Test run for /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin.IntegrationTests/bin/Debug/netcoreapp2.0/FirebaseAdmin.IntegrationTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:09.4885137]     FirebaseAdmin.IntegrationTests.FirebaseAuthTest.SignInWithEmailLink [FAIL]
  X FirebaseAdmin.IntegrationTests.FirebaseAuthTest.SignInWithEmailLink [935ms]
  Error Message:
   FirebaseAdmin.Auth.FirebaseAuthException : Unexpected HTTP response with status: 400 (BadRequest)
{
  "error": {
    "code": 400,
    "message": "OPERATION_NOT_ALLOWED",
    "errors": [
      {
        "message": "OPERATION_NOT_ALLOWED",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

  Stack Trace:
     at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndReadAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin/Util/ErrorHandlingHttpClient.cs:line 114
   at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndDeserializeAsync[TResult](HttpRequestMessage request, CancellationToken cancellationToken) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin/Util/ErrorHandlingHttpClient.cs:line 62
   at FirebaseAdmin.Auth.FirebaseUserManager.PostAndDeserializeAsync[TResult](String path, Object body, CancellationToken cancellationToken) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs:line 340
   at FirebaseAdmin.Auth.FirebaseUserManager.GenerateEmailActionLinkAsync(EmailActionLinkRequest request, CancellationToken cancellationToken) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs:line 263
   at FirebaseAdmin.Auth.FirebaseAuth.GenerateSignInWithEmailLinkAsync(String email, ActionCodeSettings settings, CancellationToken cancellationToken) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs:line 813
   at FirebaseAdmin.Auth.FirebaseAuth.GenerateSignInWithEmailLinkAsync(String email, ActionCodeSettings settings) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs:line 792
   at FirebaseAdmin.IntegrationTests.FirebaseAuthTest.SignInWithEmailLink() in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs:line 470
   at FirebaseAdmin.IntegrationTests.FirebaseAuthTest.SignInWithEmailLink() in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs:line 487
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:30.9377026]     FirebaseAdmin.IntegrationTests.FirebaseAuthTest.PasswordResetLink [FAIL]
  X FirebaseAdmin.IntegrationTests.FirebaseAuthTest.PasswordResetLink [2s 170ms]
  Error Message:
   System.Net.Http.HttpRequestException : Response status code does not indicate success: 400 (Bad Request).
  Stack Trace:
     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at FirebaseAdmin.IntegrationTests.FirebaseAuthTest.ResetPasswordAsync(ResetPasswordRequest data) in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs:line 607
   at FirebaseAdmin.IntegrationTests.FirebaseAuthTest.PasswordResetLink() in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs:line 450
   at FirebaseAdmin.IntegrationTests.FirebaseAuthTest.PasswordResetLink() in /Users/horatiulazu/Desktop/Programming-Projects/firebase-admin-dotnet/FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs:line 460
--- End of stack trace from previous location where exception was thrown ---

Test Run Failed.
Total tests: 23
     Passed: 21
     Failed: 2
 Total time: 34.8007 Seconds

```

## Solution
Login to the Firebase Console, then go to: `Authentication` -> `Email/Password` -> `Enable`, and then enable the `Email Link (Passwordless Sign-In)` as well. 

After performing the changes, all tests passed.

## Ideas/Proposal/Fixes
1. Add the instructions to the CONTRIBUTE.md file to manually enable the fix.

2. It would be nice to have an appropriate error message on a possible fix for the test failure; I noticed other integration tests implement this.

**Comment by hiranya911** [comment]
Thanks @MathBunny. Feel free to send in a PR with a fix. I think easiest would be to update the instructions.
