### ISSUE TITLE
SenderId mismatch

### ISSUE THREAD

**Issue by anoam** [firebase/firebase-admin-dotnet#296]
Hey there!
I'm trying to start using Firebase for push notifications.
I've downloaded the key file and trying to run this code.
```
var sender = FirebaseApp.Create(
  new AppOptions
    {                
       Credential = GoogleCredential.FromFile("/path/to/my/key.json")
     }
);

var message = new Message
  {
    Data = new Dictionary<string, string>
      {
        { "foo", "bar" }
      },
     Token = "" // the token is here
  };

await FirebaseMessaging.DefaultInstance.SendAsync(message);
```

But I get the following exception:
```
System.AggregateException: One or more errors occurred. (SenderId mismatch)
 ---> FirebaseAdmin.Messaging.FirebaseMessagingException: SenderId mismatch
   at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndReadAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndDeserializeAsync[TResult](HttpRequestMessage request, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAsync(Message message, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message, Boolean dryRun, CancellationToken cancellationToken)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message, Boolean dryRun)
   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message)
```
Would you kindly help me to get rid of this?

**Comment by hiranya911** [comment]
It generally means the token and the credential come from 2 different projects. See https://firebase.google.com/docs/reference/admin/dotnet/namespace/firebase-admin/messaging#messagingerrorcode

Please use StackOverflow for usage questions and debugging help.

**Comment by autoprog** [comment]
hi,
update: 2025

      async Task Api_SendToTokenAsync()
            {
   
          var registrationToken = "cB0E5BH-RyOq0O.........";

  
           var message = new Message()
           {
               Data = new Dictionary<string, string>()
               {
                   { "score", "850" },
                   { "time", "2:45" }, 
               },  
               Token = registrationToken,
           };

    

           try
           {
               string response = await FirebaseMessaging.DefaultInstance.SendAsync(message);

               Console.WriteLine("Successfully sent message: " + response);
           }
           catch (Exception ex)
           {
          
               Console.WriteLine("SendAsync-error: \n" + ex.ToString() + "\n\n");
           }

     }

//---------------
.NET9.0
Receive Host Push ok
key json load...

thanks,
Carlos.
